packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  better-auth: ^1.4.18
  ai: ^6.0.3
  "@polar-sh/better-auth": ^1.6.4
  "@ai-sdk/react": ^3.0.3
  "@better-auth/expo": ^1.4.18
